// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdpenccsqlndvdwubwil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcGVuY2NzcWxuZHZkd3Vid2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDc4NzMsImV4cCI6MjA2MjUyMzg3M30.Xf5zkxR_eGVKNVDTDaicJnmLmKSJseh_dMR7sob6uMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);